version: 2
jobs:
  build:
    docker:
      - image: gjyoung1974/complyapp:latest
    working_directory: /source
    steps:
      - run: |
          --env gh_token=${GITHUB_TOKEN} --env gh_user=${GITHUB_USER} --env gh_email=${GITHUB_EMAIL} --env gh_repo=${GITHUB_REPO} gjyoung1974/complyapp:latest
