version: 2
jobs:
  build:
    docker:
      - image: gjyoung1974/complyapp:latest
    working_directory: /source
    steps:
      # - checkout
      # # ... steps for building/testing app ...

      # - setup_remote_docker:   # (2)
      #     docker_layer_caching: true # (3)

      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      # - run:
      #     name: render
      #     command: |
      #       set -x
      #       VER="17.03.0-ce"
      #       curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
      #       tar -xz -C /tmp -f /tmp/docker-$VER.tgz
      #       mv /tmp/docker/* /usr/bin

      # build and push Docker image
      - run: |
          docker run --env gh_token=${GITHUB_TOKEN} --env gh_user=${GITHUB_USER} --env gh_email=${GITHUB_EMAIL} --env gh_repo="soc2-policy-templates" gjyoung1974/complyapp:latest
