version: 2
jobs:
  build:
    docker:
      - image: busybox
    working_directory: /home/circleci/image-builder
    steps:
      - run: docker run --env gh_token=${GITHUB_TOKEN} --env gh_user=${GITHUB_USER} --env gh_email=${GITHUB_EMAIL} --env gh_repo="soc2-policy-templates" ${COMPLY_APP_IMAGE}
