version: 2
jobs:
  build:
    ubuntu-14.04-XXL:
      machine:
        docker_layer_caching: true
      working_directory: /home/circleci/image-builder
      environment:
        IMAGE_REPO: circleci/build-image
        TARGET: ubuntu-14.04-XXL
        _TARGET: ubuntu-14_04-XXL
      steps:
        - run:
            command: |
              docker run --env gh_token=${GITHUB_TOKEN} --env gh_user=${GITHUB_USER} --env gh_email=${GITHUB_EMAIL} --env gh_repo="soc2-policy-templates" ${COMPLY_APP_IMAGE}
